rubyforgood/abalone

app/models/tagged_animal_assessment.rb, db/migrate/20190726191836_create_tagged_animal_assessments.rb, db/schema.rb, spec/factories/tagged_animal_assessments.rb, spec/models/tagged_animal_assessment_spec.rb
Resolves #006
Created the Tagged Animal Assessment model with matching migration.
=> Create Tagged Animal Assessment model and migration.

app/models/untagged_animal_assessment.rb, db/migrate/20190726191528_create_untagged_animal_assessments.rb, db/schema.rb, spec/factories/untagged_animal_assessments.rb, spec/models/untagged_animal_assessment_spec.rb
Adds UntaggedAnimalAssessment model and migration
=> Add UntaggedAnimalAssessment model

db/migrate/20190726211013_change_wild_collection_field_types.rb, db/schema.rb
Switches several fields from string to numeric or string to date. Renames "final_holding_facility_date_of_arrival" to "final_holding_facility_and_date_of_arrival".
Add Migration
=> Switch wild collection model fields to numeric and date

spec/factories/population_estimates.rb, spec/models/facility_spec.rb, spec/models/pedigree_spec.rb, spec/models/population_estimate_spec.rb, spec/models/spawning_success_spec.rb
- I have added tests that prove my fix is effective or that my feature works,
- New and existing unit tests pass locally with my changes ("bundle exec rake"),
add some factories and more testing
nothing new
this is nothing but testing
=> add factories and more testing

app/assets/javascripts/file_uploads.js, app/assets/javascripts/navbar.js, app/assets/stylesheets/file_uploads.css, app/views/facilities/_form.html.erb, app/views/facilities/edit.html.erb, app/views/facilities/index.html.erb, app/views/facilities/new.html.erb, app/views/facilities/show.html.erb, app/views/file_uploads/index.html.erb, app/views/file_uploads/new.html.erb, app/views/file_uploads/upload.html.erb, app/views/layouts/application.html.erb
Look and feel changes for the facilities views and the file upload form.
=> Basic Look & Feel

app/views/layouts/application.html.erb
Clicked on the menu items to navigate to the corresponding pages.
=> Add file uploads top level menu with dropdown submenu

app/views/home/show.html.erb
Added project summary paragraph and press links to About page. May need further styling. Could replace social media links with icons in a later PR.
=> About page

Capfile, Gemfile, Gemfile.lock
=> Add capistrano delayed_job

README.md
I added Architectural Constraints and Other Considerations sections based off the discussion we had in our pairing session today.
If you had another example you've seen in the wild of overcomplicating code or not keeping it beginner-friendly, maybe we should add that instead to the ```Other Considerations```section.
=> add architectural constraints and other considerations sections

app/jobs/concerns/import_job.rb, app/lib/csv_importer.rb, app/models/tagged_animal_assessment.rb, app/models/untagged_animal_assessment.rb, db/sample_data_files/wild_collection/example_of_wild_collection_data.csv, db/schema.rb, db/seeds.rb, spec/features/upload_tagged_animal_assessments_spec.rb, spec/features/upload_untagged_animal_assessments_spec.rb, spec/jobs/wild_collection_job_spec.rb, spec/lib/csv_importer_spec.rb, spec/support/csv/Tagged_assessment_invalid_values.csv, spec/support/csv/Tagged_assessment_valid_values.csv
Resolves #102  
Feature to rollback all created records if we encounter a single failed import when processing a file.
Refactored `import_job.rb` to support such failure, report appropriate fail message, and set appropriate file status.
Wrote spec test for `CsvImporter`, and tested it locally.
=> Completely fail on import error

app/models/facility.rb, app/models/tank.rb, db/migrate/20200404212335_create_tanks.rb, db/schema.rb, spec/factories/tanks.rb, spec/models/tank_spec.rb
addressing #127
Creates a new tank data model.
=> start a tank data model

app/models/post_settlement_inventory.rb, app/models/tank.rb, db/migrate/20200404222231_create_post_settlement_inventories.rb, db/schema.rb, spec/factories/post_settlement_inventories.rb, spec/models/post_settlement_inventory_spec.rb
Adds Post Settlement Inventory model
=> add post settlement inventory model

app/models/measurement.rb, app/models/operation.rb, db/migrate/20200405181908_create_measurements.rb, db/migrate/20200405182059_create_operations.rb, db/migrate/20200405184451_add_measurement_date_to_measurements.rb, db/migrate/20200405190459_add_dates_to_operations.rb, db/schema.rb, spec/factories/measurements.rb, spec/factories/operations.rb, spec/models/measurement_spec.rb, spec/models/operation_spec.rb
Begins to address #131 through creation of a measurements and an operations table.
Measurements are individual actions taken on a specific tank that do not change the state of the tank. Measurements get the current state of the tank at a specific date for a specific type of measurement. Eg: length, number of animals, temperature, etc... 
Operations are individual actions taken on a specific tank that change the state of the tank. Operations handle the consolidation input data where animals are added and removed from two distinct tanks.
Resolves #001 
* This change requires a …
=> Tank Operations

README.md
Some guidance on how to use docker-compose and the make targets.
* Documentation update (_development_)
=> add usage instructions to the Docker section of the README

Makefile, README.md, docker-compose.yml
There is no `make` option to seed the database on a docker environment so I added it.
Not sure if the naming is ok but I opted for `make database_seeds` to trigger `rails db:seed` on the docker container.
Ran `make database_seeds` and then confirmed that the database was seeded.
=> Add seeds makefile

app/assets/stylesheets/application.scss, app/controllers/file_uploads_controller.rb, app/models/processed_file.rb, app/views/file_uploads/index.html.erb, config/routes.rb, spec/features/delete_failed_file_upload_spec.rb, spec/models/processed_file_spec.rb
=> Create remove failed csv button

app/controllers/file_uploads_controller.rb, app/views/file_uploads/index.html.erb, config/initializers/mime_types.rb, spec/factories/processed_files.rb, spec/features/download_CSV_file_spec.rb, spec/features/download_csv_file_spec.rb
Resolves #242  
Create link to download csv files.
=> ADD download link

config/database.yml, docker-compose.yml
=> Adds default DB config again. Modifies rubocop command in docker-compose to autofix

app/views/file_uploads/upload.html.erb, spec/features/csv_upload_confirmation_spec.rb
=> Add link to view all files after uploading a file

app/controllers/tanks_controller.rb, app/views/tanks/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/tanks/show_spec.rb
Resolves #317 
This PR creates a view for the tank show page
List any dependencies that are required for this change. (gems, js libraries, etc.)
Include anything else we should know about. -->
From Power Abalone Create team
After updating and re-running the seed file, you can visit a tanks show page through the URL (i.e. http://localhost:3000/tanks/4). A feature test has also been created for this page.
=> [317] Show Tank Record

app/controllers/tanks_controller.rb, app/models/tank.rb, app/views/layouts/application.html.erb, app/views/tanks/index.html.erb, app/views/tanks/show.html.erb, spec/features/tanks/index_spec.rb
Resolves #313
This PR builds an index page for tanks.
New feature
Wrote a feature spec and tested that the page works locally.
=> [313] Added an index view for tanks

app/controllers/families_controller.rb, app/models/family.rb, app/views/families/_form.html.erb, app/views/families/edit.html.erb, app/views/families/index.html.erb, app/views/families/new.html.erb, app/views/families/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/families/create_spec.rb, spec/features/families/delete_spec.rb, spec/features/families/index_spec.rb, spec/features/families/update_spec.rb
#
Resolves #312, #314, #316, #318, #320    
Adds CRUD pages for `Family` resource. 
A few feature specs included. New resource routes for `Family` can be navigated to in order to verify.
=> Add CRUD pages for family resource

app/controllers/tanks_controller.rb, app/models/facility.rb, app/models/tank.rb, app/views/tanks/_form.html.erb, app/views/tanks/index.html.erb, app/views/tanks/new.html.erb, app/views/tanks/show.html.erb, spec/features/tanks/new_spec.rb
Resolves #315
This allows a user to create a new Tank via a `new` tank form
A user can view the form properly. The form can be filled out and see that it was successfully created on the show page.
=> [315] Create New Tank

app/models/user.rb, db/migrate/20200922142446_add_role_to_users.rb, db/schema.rb, db/seeds.rb, spec/models/user_spec.rb
Resolves #338 
This PR adds the role column to the users table and sets a default role of 'user' when a user is created.
New feature
Added a model spec and created a new user record in the DB to see if a default role was set.
=> [338] Feature - Added role column to users table

app/controllers/users_controller.rb, config/routes.rb
Resolves #339 
In this PR, I created the users controller and added a before_action to check if user is an admin
New feature
Can't really be tested because views are not in place. Those are separate stories.
=> [339] Feature - Admin configuration for users controller

app/assets/stylesheets/application.scss, app/javascript/packs/styles.scss, app/javascript/packs/tailwind.js, app/views/layouts/application.html.erb, package.json, postcss.config.js, yarn.lock
Resolves #274 
Installed Tailwindcss via yarn. Tailwinds was added as a PostCSS plugin. A tailwind.js and styles.scss file was included under packs. Bootstrap import was removed. This will allow developers to easily customize the CSS.
Dependencies:
- Tailwindcss [https://tailwindcss.com/docs/installation]
- This does break minor styles with no effect to functionality (ie table width and button placement). Follow up PR's will include fixes for this.
Checked all buttons and links to verify that they are working and all pages still include full functionality.
=> [274] Add Tailwinds via Webpack

Dockerfile, docker-entrypoint.sh
Please also include relevant motivation and context.
Guide questions:
- What motivated this change (if not already described in an issue)?
We were not able to start up the docker environment using `docker-compose`. It was throwing an error about webpacker. Since the dockerfile was already needing some attention we decided to change it a bit.
- What alternative solutions did you consider?
Trying to fix with the old dockerfile didn't look too promising.
- What are the tradeoffs for your solution?
It works now.
List any dependencies that are required for this change. (gems, js libraries, etc.)
* No changes.
Just follow up the README instruction for the docker environment.
=> Use alpine and fix yarn install

app/controllers/tanks_controller.rb
This PR aims to fix an n+1 query on the tanks page.
-->
Resolves #365 
=> Include facilities for tanks to avoid n+1 query

app/models/post_settlement_inventory.rb, app/models/tank.rb, db/migrate/20200923134705_drop_post_settlement_inventories.rb, db/schema.rb, spec/factories/post_settlement_inventories.rb, spec/models/post_settlement_inventory_spec.rb, spec/models/tank_spec.rb
Resolves #328 
Removes PostSettlementInventory model and related code.
* Refactoring
Ran entire test suite
=> [328] Remove post settlement inventory model and related code

Makefile, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/index.html.erb, spec/features/users/delete_spec.rb, spec/features/users/index_spec.rb
=> [344] Allows deletion of users

app/controllers/users_controller.rb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, spec/features/users/update_spec.rb
Resolves #343 
As an admin I want to update a user for an organization
Feature tests implemented and also some basic exploratory tests.
=> [343] Implements user edit functionality

app/controllers/file_uploads_controller.rb, app/helpers/file_uploads_helper.rb, app/models/file_upload.rb, app/views/animals/show.html.erb, app/views/file_uploads/csv_index.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/factories/file_upload.rb, spec/features/file_upload/csv_index_spec.rb
Add an index page scoped to organization that shows file uploads, names,
timestamps, status.
Co-authored-by: darrendc <darren.dcosta@powerhrg.com>
Co-authored-by: Michelle Hey <michelle.hey@powerhrg.com>
Co-authored-by: Benjamin Krigel <benjamin.krigel@gmail.com>
Resolves #244  
Add an index page scoped to organization that shows file uploads, names,
timestamps, status. This is for the new ActiveStorage upload interface.
Click testing, along with feature specs that upload files and create resource shown on page.
=> Add csv upload index

app/controllers/animals_controller.rb, app/models/animal.rb, app/models/cohort.rb, app/views/animals/_form.html.erb, app/views/animals/index.html.erb, app/views/animals/show.html.erb, app/views/cohorts/show.html.erb, db/migrate/20200924153501_add_cohort_id_to_animals.rb, db/schema.rb, db/seeds.rb, spec/factories/animals.rb, spec/factories/cohorts.rb, spec/features/animals/create_spec.rb, spec/features/animals/index_spec.rb, spec/features/animals/show_spec.rb, spec/models/animal_spec.rb, spec/models/cohort_spec.rb
Resolves #405
This PR sets up the association between cohorts and animals
New feature
I have written feature specs and tested it manually in the application.
=> [405] Feature - Setup Cohort association to animals

app/controllers/animals_controller.rb, app/jobs/import_animals_job.rb, app/models/animal.rb, app/models/cohort.rb, app/views/animals/_form.html.erb, app/views/animals/index.html.erb, app/views/animals/show.html.erb, app/views/cohorts/_form.html.erb, app/views/cohorts/index.html.erb, app/views/cohorts/show.html.erb, db/migrate/20200924210137_rework_animal_tags.rb, db/schema.rb, spec/factories/animals.rb, spec/features/animals/create_spec.rb, spec/features/animals/destroy_spec.rb, spec/features/animals/index_spec.rb, spec/features/animals/show_spec.rb, spec/features/animals/upload_spec.rb, spec/features/cohorts/create_spec.rb, spec/fixtures/animals.csv, spec/lib/csv_importer_spec.rb
Co-authored-by: Vinicius Gama <vinicius.sgama@gmail.com>
-->
Resolves #397 
=> Reworked animal tags to be in a single string column

app/controllers/measurements_controller.rb, app/javascript/packs/measurements.js, app/views/layouts/application.html.erb, app/views/measurements/new.html.erb, config/routes.rb, public/samples/animal_measurements.csv, public/samples/length_gonad_score.csv
Adds two templates for measurement csv uploads along with an interface
that can be used to select and download a sample csv
Hey @benreyn and @CraigJZ. Looking to get some feedback on whether or not this was the approach you had in mind for  #307. Obviously we can adjust the templates as needed. But also want to make sure the selections in the UI were what you had in mind, or if there was something I'm missing here. Let me know your thoughts!
Partially resolves  #307 
First step for #307. This provides csv templates for the upload of measurements. It includes headers and a few rows of sample data.
Manually, specs will follow with the next task which is the uploading and parsing of completed csv templates.
=> Add templates, ui for measurement csv uploads

app/views/facilities/show.html.erb, app/views/layouts/application.html.erb, app/views/locations/_form.html.erb, app/views/locations/edit.html.erb, app/views/locations/index.html.erb, app/views/locations/new.html.erb, app/views/locations/show.html.erb
Follows #411 
* Style Updates (Non-breaking change)
Tested all links on every page. Also ran a test create of a new location.
=> Location pages updates

README.md, config/deploy/production.rb
This branch updates the hosting information listed in the documentation and removes old deploy config.
=> Update hosting information.

spec/factories/animals.rb, spec/factories/enclosures.rb, spec/factories/measurement_events.rb, spec/factories/measurements.rb, spec/features/animals/index_spec.rb, spec/features/animals/show_spec.rb
Recent changes to the models and associations mean that it is now possible to make more precise and complete factories for the test suite.
This change introduces or updates Animal, Enclosure and Measurement factories and minor changes to the specs to incorporate said changes.
As these factories are used only in the test suite currently, rspec testing should be sufficient.
=> Update animal, enclosure, and measurement factories

spec/features/facilities/create_spec.rb
Resolves #428 
Add feature specs for creating a facility.
* Specs update
Tested with rspec.
=> Feature specs for creating a facility (#428)

spec/features/facilities/update_spec.rb
Resolves #429 
Add feature specs for updating a facility.
* Specs update
Tested with rspec.
=> Feature specs for updating a facility (#429)

spec/features/facilities/show_spec.rb
Resolves #430 
Add feature specs for viewing a facility.
* Spec update
Tested with rspec.
=> Feature specs for viewing a facility (#430)

spec/features/facilities/destroy_spec.rb
Resolves #431 
Add feature specs for destroying a facility.
* Spec update
Tested with rspec.
=> Feature specs for destroying a facility (#431)

db/seeds.rb
This is somewhat of a dramatic change, but in the last week the models, associations and DDL have also seen significant change. Much appreciation to all those who worked on previous iterations of the seeding process along with all the recent changes.
Resolves #399
Updates the seeds file for new models and associations. This is to be used for development purposes only as a way to populate the database with dummy information. As the information contained may not be relevant to the organizations, CSV importing should be used outside of development instead.
Ultimately I decided not to use the new factories to create associations and instead construct them manually in the seed file. This is largely because the factories still are largely test environment focused and have some fun or …
=> Update seed file for new models and associations

app/controllers/application_controller.rb, app/controllers/measurement_types_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, spec/features/measurement_types/destroy_spec.rb, spec/features/measurement_types/index_spec.rb, spec/features/measurement_types/new_spec.rb, spec/features/measurement_types/update_spec.rb
=> Require the user to be an admin to view the measurement types page

spec/features/cohorts/show_spec.rb
Resolves n/a -- missing feature spec
Add missing feature spec for cohort show.
rspec
=> Feature spec for showing a cohort

spec/features/animals/update_spec.rb
Resolves #432 
Add feature test for animal update.
rspec
=> 432 feature spec for animal

README.md
=> Readme updates for docker info

app/controllers/measurements_controller.rb, config/routes.rb
Resolves #353 
Closes issue https://github.com/rubyforgood/abalone/issues/353.
To check for the unused routes the following gem was installed locally
https://github.com/amatsuda/traceroute. The unused routes were then
checked using `rails traceroute:unused_routes`.
Reviewer should double check that no implicitly called routes have not
been removed.
* Removed unused endpoints, could potentially be breaking if one was implicity called
The routes that were removed are
```
Unused routes:
measurements#data_import
operations#create
operations#new
operations#edit
operations#show
operations#update
operations#update # Not sure why this was listed twice?
operations#destroy
```
As a second alternative to using `traceroute` a script was ran to double-check the unused routes output a rake task was …
=> Closes issue https://github.com/rubyforgood/abalone/issues/353.

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, postcss.config.js
Resolves #426 
Import Tailwind in staging.
* Bug fix (non-breaking change which fixes an issue) but it can have visual impact.
=> Import tailwind

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/current.rb, config/blazer.yml, config/initializers/blazer.rb, config/routes.rb, db/migrate/20200927001420_install_blazer.rb, db/schema.rb, lib/tasks/blazer.rake
Fixed version of #454 with rubocop fixes applied
=> Blazer fixed

app/javascript/packs/application.js, app/views/layouts/application.html.erb
=> Style notices and alerts

blazer-reporting.md, lib/tasks/blazer.rake
- [n/a] I have added tests that prove my fix is effective or that my feature works,
- [n/a] Title include "WIP" if work is in progress.
Resolves #579
This branch updates the blazer rake task to only grant select permissions on specific tables that users may need to query. 
These changes have been manually tested in the browser.
Before:
After:
=> More blazer work

app/views/users/index.html.erb, spec/features/users/index_spec.rb
Resolves #562 
Edit and Delete actions in Users table trigger ANDI's 'No accessible name' warning. To improve accessibility, I added a title to these links.
In the browser, using ANDI.
=> add title to actions to improve accessibility

app/views/animals/csv_upload.html.erb, app/views/animals/edit.html.erb, app/views/animals/index.html.erb, app/views/animals/new.html.erb, app/views/cohorts/edit.html.erb, app/views/cohorts/index.html.erb, app/views/cohorts/new.html.erb, app/views/enclosures/csv_upload.html.erb, app/views/enclosures/edit.html.erb, app/views/enclosures/new.html.erb, app/views/enclosures/show.html.erb, app/views/file_uploads/csv_index.html.erb, app/views/file_uploads/index.html.erb, app/views/file_uploads/new.html.erb, app/views/file_uploads/show.html.erb, app/views/file_uploads/show_processing_csv_errors.html.erb, app/views/file_uploads/upload.html.erb, app/views/home/show.html.erb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, app/views/measurement_types/index.html.erb, app/views/measurement_types/new.html.erb, app/views/measurements/new.html.erb, app/views/operations/index.html.erb, app/views/passwords/edit.html.erb, app/views/reports/index.html.erb
This updates `<h1>` tags across the internal pages to have a consistent style.
`text-title2` for index pages
`text-title3 mb-4` for others
This also fixes 2 missing `</section>` tags and multiple `<h1>` tag on the cohorts show page.
Test suite was run and visual inspection was done.
=> Minor fixes

app/views/enclosures/index.html.erb, spec/features/enclosures/index_spec.rb
Resolves #542 
Enclosures table lacked scope and a header for the Show/Edit/Delete actions. To improve accessibility I've added these in.
Using ANDI
=> add scope and actions header to enclosures table

app/views/facilities/index.html.erb, spec/features/facilities/index_spec.rb
Resolves #538 
The Facilities table needed a scope definition and a header for the action buttons.
Using ANDI
=> update table headers with scope and actions

app/views/file_uploads/new.html.erb, app/views/file_uploads/upload.html.erb, spec/features/file_upload/new_spec.rb
Resolves #466
Replaced Bulma classes with Tailwind classes on `views/file_uploads/new.html.erb` and `views/file_uploads/upload.html.erb` (because it felt related to #new). Added a new feature test for these files. I tried to make the UI look as close to the original as possible, but some of the button colors are a little different now.
New feature test
#new
#upload
=> Replace Bulma with Tailwind on file_uploads/new and file_uploads/upload

app/views/animals/index.html.erb, spec/features/animals/index_spec.rb
Resolves #546
Guide questions:
- What motivated this change (if not already described in an issue)?
`Listed Issue`
- What alternative solutions did you consider?
`The solution was very simple and straight forward`
- What are the tradeoffs for your solution?
`None`
`Yes`
=> Adds Animals column scope and Actions heading

.gitignore, Gemfile, Gemfile.lock, bin/rails, spec/spec_helper.rb
Resolves `Starts to resolve issue`
This provides a UI as a guide to test coverage. 
After running `bundle install` and the testing suite, run 
`$ open coverage/index.html` (*Mac Terminal*)
`$ xdg-open coverage/index.html` (*debian/ubuntu Terminal*)
=> Adds initial SimpleCov Set up

.github/workflows/brakeman.yml, Gemfile, Gemfile.lock, Makefile, README.md, app/controllers/file_uploads_controller.rb, app/controllers/locations_controller.rb, docker-compose.yml
Resolves #716 and #717 
Add brakeman gem and run brakeman in CI
=> Add brakeman

README.md, application_overview.md, blazer_reporting.md
- [n/a] I have added tests that prove my fix is effective or that my feature works,
- [n/a] New and existing unit tests pass locally with my changes ("bundle exec rake"),
- [n/a] Title include "WIP" if work is in progress.
Resolves #309 
This is a documentation update that includes changes to the README and the addition of a new Application Overview document. It also brings the instructions for setting up the row level security into a document in the repo rather than a page in the project's wiki. These changes a meant to help with onboarding new contributors.
I have proofread the documentation changes and corrected any typos.
=> Documentation update summer 2021

app/views/measurement_types/index.html.erb
Resolves #560 
This is a fix for issue #560 adding scope="col" as well as adding "ACTION" to the table headers
I ran the tests to make sure they were passing, since the table headers were not being tested before I did not add a test to check for the ACTION header. 
Before:
After:
=> Update the measurement table headers

app/views/measurements/new.html.erb
Resolves #900
Add a `margin-top` and remove a `%>` symbol at the bottom.
Just looking at the browser.
=> add margin and remove %>

app/models/animal.rb, app/models/cohort.rb, app/models/facility.rb, app/models/file_upload.rb, app/models/measurement.rb, app/models/mortality_event.rb, app/models/processed_file.rb, spec/factories/animals_shl_numbers.rb, spec/factories/processed_files.rb, spec/factories/shl_numbers.rb, spec/models/animal_spec.rb, spec/models/cohort_spec.rb, spec/models/concerns/validations.rb, spec/models/enclosure_spec.rb, spec/models/exit_type_spec.rb, spec/models/facility_spec.rb, spec/models/file_upload_spec.rb, spec/models/location_spec.rb, spec/models/measurement_event_spec.rb, spec/models/measurement_spec.rb, spec/models/measurement_type_spec.rb, spec/models/mortality_event_spec.rb, spec/models/operation_spec.rb, spec/models/processed_file_spec.rb, spec/models/user_spec.rb
Resolves #248
This PR introduces a few additional Model validations to bring Rails Model validation logic to parity with Database validations. Along the way, Model specs were added for new and existing validations. Additionally, any specs missing from existing model methods were added to the spec files during this audit.
Technically a "Bug fix."
Validation audit and model spec audit
All new validations covered by rspec. Existing validations and model methods now covered by rspec
=> Resolves issue #248: Audit models for validations

app/views/file_uploads/upload.html.erb, spec/system/file_upload/new_spec.rb
Resolves #894  
Updates the button styling for file uploads, aligning the style with the rest of the app.
Visible on a local server
Showing both hover and static state of styling:
=> Resolves issue #894: Fix color of buttons after measurement submission

public/samples/length_gonad_score_template.csv
Resolves #896 
Update the length gonad score template headers
=> add reason to template file header and empty reason fields
