Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/views/layouts/application.html.erb
Having asset compilation issues with the Bulma ruby gem.  Easier to just use the CDN.
=> Use the CDN for Bulma vs the gem.

app/models/mortality_tracking.rb, db/schema.rb, spec/models/mortality_tracking_spec.rb, spec/models/pedigree_spec.rb, spec/models/population_estimate_spec.rb, spec/models/spawning_success_spec.rb
Some of the MortalityTracking model header fields were out of sync with the excel sheets. This branch syncs them up, and they should now be consistent across excel sheet, model, and db (I think).
Also updated tests broken by added processed_file_id column.   
Unit tested in spec/models/mortality_tracking_spec.rb
=> Change mortality tracking headers

Gemfile, Gemfile.lock, README.md, app/models/facility.rb, app/models/mortality_tracking.rb, app/models/pedigree.rb, app/models/population_estimate.rb, app/models/processed_file.rb, app/models/spawning_success.rb, app/models/tagged_animal_assessment.rb, app/models/untagged_animal_assessment.rb, app/models/wild_collection.rb, lib/tasks/auto_annotate_models.rake, spec/factories/population_estimates.rb, spec/factories/processed_files.rb, spec/factories/tagged_animal_assessments.rb, spec/factories/untagged_animal_assessments.rb, spec/factories/wild_collections.rb, spec/models/facility_spec.rb, spec/models/mortality_tracking_spec.rb, spec/models/pedigree_spec.rb, spec/models/population_estimate_spec.rb, spec/models/processed_file_spec.rb, spec/models/spawning_success_spec.rb, spec/models/tagged_animal_assessment_spec.rb, spec/models/untagged_animal_assessment_spec.rb, spec/models/wild_collection_spec.rb
I've added this annotate gem: https://github.com/ctran/annotate_models
Purely to ease the development of this project.
I feel this would be a useful addition, as devs won't have to check migration files/or db itself to see what attributes the models have. And as evident from the failing tests, and incorrect attributes for some model factories.
Let me know if this needs more discussions :) I'm also open for suggestions.
* Development process improvements
Ran complete spec tests to make sure nothing else is broken. There's currently 1 failing test, that is fixed from my other PR.
=> Add annotate gem

.travis.yml, config/database.yml.travis
Resolves **the CI part** of #079
I configured the project to use TravisCI for running the test suite on Pull Requests. TravisCI was chosen because it's free, popular, easy to use, and the rubyforgood github organization already has a matching rubyforgood travis account, so getting it set up was very easy.
This change is a maintainer-facing change only, and does not affect the users in any direct fashion.
Travis has already run builds for this branch. Here is the latest: https://travis-ci.org/rubyforgood/abalone/builds/605637810
=> TravisCI integration

app/assets/stylesheets/file_uploads.css, app/views/file_uploads/index.html.erb, app/views/file_uploads/show.html.erb
Resolves #82   
- File Uploads view was without styles, and Upload Files action link was lost in the text.
- Also added columns to fields / values to help user read.
- On File Uploaded details added table styles, row highlight, rows colors, and enabled the scroll so users can view full data.
Navigate to: http://localhost:3000/file_uploads and http://localhost:3000/file_uploads/2 to see changes.
Before
* FileUploads/2:
* FileUploads:
After
* FileUploads/2:
* FileUploads:
=> Issue 82. Fix processed files view and uploaded files.

Gemfile, Gemfile.lock, app/controllers/file_uploads_controller.rb, app/models/concerns/import_job.rb, app/views/file_uploads/index.html.erb, app/views/file_uploads/show_processing_csv_errors.html.erb, config/routes.rb, spec/features/upload_tagged_animal_assessments_spec.rb, spec/features/upload_untagged_animal_assessments_spec.rb
Resolves #080 
See a more detailed info when a file is parsed.
Add a new status `Processed with errors` to avoid `Processed` and still got errors (and remains the processed file with error inside `storage` folder)
Add a new page with listing errors row by row
**IMPORTANT:** Things to define/consider:
- when you process a file with errors you will see the rows without issues in db, if you fix the file and reprocessed you'll find duplicate data if you change the filename.
- to avoid reprocess duplicated data if you want to upload the file fixed with the same name, you'll get an error
- there should be a definition if we add or not add in the db if the file has parsing errors.
- the new page processed the file in memory, it's not using db so the file with errors isn't removed from uploaded …
=> [ready to merge] [Issue #80] Better CSV Upload Errors

Gemfile.lock, app/controllers/file_uploads_controller.rb, app/jobs/concerns/import_job.rb, app/jobs/spawning_success_job.rb, app/jobs/untagged_animal_assessment_job.rb, app/jobs/wild_collection_job.rb, app/lib/csv_importer.rb, app/models/spawning_success.rb, app/models/tagged_animal_assessment.rb, app/models/untagged_animal_assessment.rb, app/models/wild_collection.rb, db/seeds.rb
Because the `db/seeds` and the `ImportJob` jobs were both importing CSVs, it made sense to consolidate the business logic of importing CSV data in one place. The `CsvImporter` seems a good place.
* Made `CsvImporter` responsible for doing the actual import
This makes the background jobs a lot simpler by deferring to the importer to do the actual data processing.
`CsvImporter` refactored from a module to a class so that an individual import action is represented by an instance of an importer. A class method `import()` remains that maintains the previous method signature so the existing call sites for CSV import stay the same.
* `CsvImporter::CATEGORIES`
This is a simpler list of the human-readable strings that are the categories of data to import. This is the **One True Place**™ where …
=> Simplify CSV import

app/controllers/file_uploads_controller.rb, app/jobs/concerns/import_job.rb, app/models/temporary_file.rb, db/migrate/20200109183112_create_temporary_files.rb, db/migrate/20200109184825_add_temporary_file_id_to_processed_files.rb, db/schema.rb, spec/factories/temporary_files.rb, spec/features/upload_tagged_animal_assessments_spec.rb, spec/features/upload_untagged_animal_assessments_spec.rb, spec/jobs/concerns/import_job.rb, spec/jobs/wild_collection_job_spec.rb, spec/models/temporary_file_spec.rb
Resolves https://github.com/rubyforgood/abalone/issues/104
This PR addresses the problem where because a heroku worker runs on a different app, it cannot access the local disk storage of the webapp, where the csv files live.
To solve that, this PR does the following:
* Instead of taking csv uploads and writing it to disk, shove it into a `TemporaryFile` object.
* When the `ImportJob` runs, grab the contents of that `TemporaryFile` object, write it to disk, and continue as before.
Note: this code change doesn't delete the `TemporaryFile` objects or clean what's on disk - let's open that request as a new low-priority issue.
We might want to add some architectural notes to the README about this, but I'd like for either someone else to do that if it's needed for this PR before merge, or to do …
=> Store uploaded csv files in database not on disk

app/models/processed_file.rb, app/models/temporary_file.rb, lib/tasks/scheduler.rake, spec/lib/tasks/scheduler_rake_spec.rb, spec/rails_helper.rb, spec/support/shared_contexts/rake.rb
This PR:
- Resolves #112
- Creates a rake task to delete or warn about stale TemporaryFiles
- Adds a has_one/belongs_to relationship between temporary and processed files
- Adds rspec tests for the new rake task
- Creates a shared context in rspec for testing future rake tasks
Type of change:
New feature (non-breaking change which adds functionality)
Discussion Points:
- On the data side, I noticed there was no relationship between ProcessedFiles and TemporaryFiles in their respective models. I created a has_one/belongs_to relationship between the two for easier lookup in the rake task. Please let me know if this should be one-to-many instead, or if there was a reason to not have a relationship specified in the model.
- From a feature perspective, I didn't see a way for a user to delete a …
=> [Issue 112] Create job called by daily cron that deletes processed TemporaryFiles

spec/models/consolidation_report_spec.rb
There were a few warnings occuring when the tests were ran, which were a
bit rough to think through when reviewing for test failures.
I believe they may also have been indicating that the expectations we
thought we had in place were not actually in place.
=> Resolve warnings in Test Suite

app/models/operation.rb, app/models/operation_batch.rb, app/models/tank.rb, db/migrate/20200513172140_create_operation_batches.rb, db/schema.rb, spec/factories/families.rb, spec/factories/operation_batches.rb, spec/factories/operations.rb, spec/features/group_operations_in_operation_batches_spec.rb, spec/models/operation_batch_spec.rb
See: https://www.github.com/rubyforgood/abalone/issues/140
See #140
Staff want to be able to group operation(s) in order to understand them at a different level of granularity. (Kind of like how we group related commits into a PR)
Purely through RSpec, as there is no UI for viewing or managing Operations at this time.
=> ✨ Related Operations may be grouped into OperationBatches

Dockerfile, Makefile, bin/dbinit/001-create-databases.sql, docker-compose.yml, entrypoint.sh
No current issue.
Experimental.
In an effort to make getting a development environment up and running easier, this applied judicious automation with Docker, docker-compose, and a Makefile.
TODO:
- so that a developer could choose to use the container for the database while running all the Ruby on their host computer? Risk: port conflicts on developer computers who already have Postgres for Windows or Postgres.app installed and might not know how or want to do something about it.
- This might be as simple as:
* Install [Chocolatey](https://chocolatey.org/install) (something similar to HomeBrew for Windows)
* Use Chocolatey to install make: `choco install make` in a command window running as Administrator
* This change requires a documentation update (for developers)
On a development …
=> 🚧  WIP: A Very Docker Development Environment

config/database.yml, docker-compose.yml
Forward the `db` service's port to the host's loopback interface, so that a developer could choose to use docker-compose only for a container to run the database while running all the Ruby processes on their host computer. `127.0.0.1:5432:5432` was chosen over `5432:5432` so that the PostgreSQL would not be available to all other computers on the host computer's network (say, a coffee shop wifi).
This also updates the development database config to default to using "localhost" for the database host to support a typical dev environment where Ruby processes are running on the host OS. It accepts an environment variable `ABALONE_DATABASE_HOSTNAME` (named in the style of the existing `ABALONE_DATABASE_PASSWORD` variable) to override the database hostname. The compose file has been updated to …
=> default the db service to listen on host's localhost:5432

.travis.yml
This does *not* affect testing pull requests.
With both **Build pushed branches** and **Build pushed pull requests** ON at Travis CI, pull requests trigger 2 builds.
This config change filters the branches considered for the **Build pushed branches** to only build when master has a push (e.g. when it is updated by a merge from a pull request). **Build push pull requests** will still trigger builds for branches associated with pull requests.
=> only test on pushes to master branch

Makefile
`make` defaults to running the first target. So before this change, if someone types only "`make`" it will scrap their development environment and setup a whole new one. That's probably not a good default.
=> make dev_env the default make target

config/database.yml
Having this constraint forces developers to have the username postres, and can 
cause unessesary install issues for those who are less familiar
with pg. I suggest removing this constraint all together for the dev
environment as I generally find it unnecessary to have a username/pasword on
the dev env.
Resolves #265 
Please also include relevant motivation and context.
Guide questions:
- What motivated this change (if not already described in an issue)?
Decrease setup difficulty.
- What alternative solutions did you consider?
Could use env vars for username password on dev env, but I find that it is usually not necessary to enforce dev env passwords for the db.
- What are the tradeoffs for your solution?
not sure. willing to discuss.   
List any dependencies that are required for this …
=> Removed the dev env db username/password

README.md, config/database.yml, docker-compose.yml
This ought to ensure that the make targets work by using a consistent set of database credentials in the docker-composed environment.
* `DATABASE_URL` provides all the app-derivative services with the connection information for the postgres server running in Docker.
* `POSTGRES_USER` is set to "dockerpg" for the database server. This overrides [the postgres image's default "postgres" user](https://github.com/docker-library/docs/blob/master/postgres/README.md#postgres_user). My hope here is to increase the usefulness of error messages about connecting to the database because they will complain about a "dockerpg" user which will be distinct from the usual "postgres" user that exists in standard PostgreSQL installs on the host.
The [database username and password were removed from …
=> set db credentials for running the app via compose

README.md
The Travis CI badge was not in the README.md file.  This pull request adds this in.  The result is at https://github.com/jhsu802701/abalone/tree/travis_ci_badge.
=> Added the Travis CI badge

app/controllers/tanks_controller.rb, app/models/measurement_event.rb, app/models/tank.rb, app/views/tanks/index.html.erb, spec/features/tanks/destroy_spec.rb, spec/features/tanks/index_spec.rb
Resolves #321
This ticket sets up the destroy action to delete tanks
New feature
Login in to the app. Go to tanks index view. Click the trash can to delete a tank.
=> [321] Can delete tanks

app/controllers/tanks_controller.rb, app/views/tanks/edit.html.erb, app/views/tanks/index.html.erb, app/views/tanks/show.html.erb, spec/features/tanks/update_spec.rb
Resolves #319
Give the ability for an admin user to edit and update a Tank record from the Tanks index page
Include feature test to make sure an existing Tank record can have it's Facility association and Name updated, and the updated record displays properly on the Tank show page.
=> [319] Set up TanksController #edit and #update actions

app/controllers/users_controller.rb, app/views/users/show.html.erb, spec/controllers/users_controller_spec.rb, spec/features/users/show_spec.rb
Resolves #342
* Allow admin users to view user show page, which displays the user's email and organization name. Non-admin users will be redirected back to the application home page.
* Includes a bug fix in the `UsersController` where it was inheriting from `ApplicationControler` instead of `ApplicationController`
* Feature test to ensure that an admin user can properly view a user's show page, and a non-admin user cannot gain access to the show view.
* Controller test that expects a 200 response for admin users and a 302 redirection for non-admins
=> [342] Set up UsersController#show

app/controllers/passwords_controller.rb
Resolves #427 
Devise has deprecated the `:bypass` option for the `sign_in` method. It will be removed in future versions.
We should use the `bypass_sign_in` method instead.
* Specs are passing
* I am able to change a user's password locally
Deprecation warning before the change:
No more Devise deprecation warning after the change:
Password update is still working:
=> Fix the Devise bypass option deprecation warning

.gitignore, app/models/concerns/organization_scope.rb, spec/factories/measurement_events.rb, spec/models/animal_spec.rb, spec/models/cohort_spec.rb, spec/models/concerns/validations.rb, spec/models/enclosure_spec.rb, spec/models/facility_spec.rb, spec/models/location_spec.rb, spec/models/measurement_event_spec.rb, spec/models/measurement_spec.rb, spec/models/measurement_type_spec.rb, spec/models/operation_spec.rb, spec/models/organization_spec.rb, spec/models/user_spec.rb
Resolves https://github.com/rubyforgood/abalone/issues/438 
**Description**
1. Add Organization presence validation to OrganizationScope and add spec coverage to relevant models
In the process of writing specs, fixed the broken measurement_events factory which had incorrect associations
2. Added `.generators` to `.gitignore` as RubyMine automatically creates it
**Type of change**
Spec coverage of organization validation
**How Has This Been Tested?**
Tested with RSpec
=> Add Organization presence validation to OrganizationScope and add spec coverage to relevant models

app/models/facility.rb, spec/factories/facility.rb, spec/models/concerns/validations.rb, spec/models/facility_spec.rb
Resolves #436  
Add model level validation to `Facility` which do
- validates the presence of the name
- validates the presence of code
- validates the uniqueness of code, scoped to organization_id
Tested with rspec matcher but with some issue regarding shoulda-matchers issue here https://github.com/thoughtbot/shoulda-matchers/issues/814
Instead of using `organization` object, it is scoped to `organization_id`
=> [#436] Add Facility model validation

Gemfile, Gemfile.lock
Un-pins faker from master branch. This was leading dependabot to open a PR every time Faker gem's master was updated. We can probably just use the latest release tag.
Specs still good, we weren't using anything not cut into a gem version.
=> Unpin faker gem from master

app/views/layouts/application.html.erb
We are importing the following TailwindCSS styles through webpacker, so I think we need to add `<%= stylesheet_pack_tag 'application' %>` for them to work in production.
```
tailwindcss/base
tailwindcss/components
tailwindcss/utilities
```
=> Add stylesheet pack tag for bringing in tailwindcss styles.

app/models/animal.rb, app/models/cohort.rb, app/models/mortality_event.rb, db/migrate/20201020103647_create_mortality_events_table.rb, db/schema.rb, db/seeds.rb, spec/factories/mortality_events.rb, spec/models/animal_spec.rb, spec/models/cohort_spec.rb, spec/models/mortality_event_spec.rb
-->
Resolves #433 
As per the issue, I have added a mortality event table which has a cohort and animal. There are methods to check how many mortalites there are in a cohort, and methods returning a boolean from the animal model to check if they are alive or dead. I have added tests for this too.
=> Add concept of mortality rate to animals and cohort

app/views/home/index.html.erb, spec/features/home_page_statistics_spec.rb, spec/features/users/show_spec.rb
Resolves #470
Added organization name onto homepage, for logged in users. To keep styling consistent, I tried to stick to existing patterns and use the same classes. Below the hero image, there is now a headline reading "Your organization: [organization name]".
Current user tests have been updated to reflect changes. Logged in users who are not admins can now see their organization name on the page. Additional tests were added to verify that visitors who are not logged in cannot see this information.
=> display current organization when user is logged in

db/seeds.rb
I noticed on following the setup instructions that `rake db:seed` fails with the error `NoMethodError: undefined method `create' for nil:NilClass`. It looks like before it has been persisted, you can't call Animal.mortality_event.create.
I've fixed this by assigning the result of `MortalityEvent.create` to `dead_animal.mortality_event`.
Tested through dropping the database locally, creating it afresh with `rake db:create` and `rake db:migrate` and running the seed task. Confirmed that this seeds the database correctly.
(Before)
(After)
=> Fix DB seed task

yarn.lock
Github alerted us to a high-severity security vulnerability in
node-forge, a dependency of the selfsigned package, which is a
dependency of webpack-dev-server
This commit was created by running...
```
$ yarn upgrade webpack-dev-server
```
to upgrade these dependencies and eliminate this security vulnerability
=> Update webpack-dev-server dependencies

app/views/layouts/application.html.erb
Resolves #467 
This branch reorganizes the main navigation bar to place the admin-only items in a drop-down menu item and moves the Github button under the _More_ nav item. 
This fixes the nav bar running off of smaller screen sizes that are still larger than the first break-point when admin nav items are present.
- Test suite was run
- Manually testing on 13' laptop screen
Before:
After:
=> Reorganize nav bar

config/routes.rb, lib/tasks/blazer.rake, spec/features/users/update_spec.rb
This branch makes a couple of modifications to the blazer setup  -
First, it updates the blazer rake task so it only creates or drops the organization roles when not run in production. This is to conform to our current hosting, which requires those roles be set manually prior to running the task.
Second, it wraps the blazer mount in devise's authenticate method to provide a more user friendly error than blazer's standard one if an unauthenticated users tries to access that route. This may not be needed once when update the blazer and report routes.
Once merged, I'll test the updated rake task on abalone-staging and make any necessary tweaks.
=> Blazer rake task modifications

.gitignore, README.md, blazer-reporting.md, config/environments/development.rb
Closes #524 
This PR adds documentation for:
- Getting blazer set up locally
- Adding a new organization locally
- Setting up blazer in production (under our current setup)
- Adding a new organization in production
The implementation of the local_env.yml file is driven by simplicity. If anyone has strong feelings about a different method for managing local environment variables, I am fine with changing this. 
The failing spec in master should be fixed by #523
=> Blazer documentation

db/seeds.rb
I ran `bin/setup` and then ran `rake db:seed`, which resulted in an error being raised. I believed that the rake command had failed to populate the database correctly. Instead, it failed because the seeds had already been loaded into the database. 
The problem was that the `find_or_create` method was looking at `date_time_collected` which varied between the first run and second run. This caused the find part to never match and the create portion failed because tag had already been used and raised a uniqueness validation error. 
I can run `rake db:seeds` over and over again and not get any errors.
=> makes seeds file idempotent

app/views/animals/index.html.erb, spec/features/animals/index_spec.rb
Resolves #481  
In #419 the page was converted from bootstrap to Tailwind. During that process the link was commented out. I uncommented it and added additional Tailwind classes to make the styling match the buttons next to the link. I believe I have successfully recreated every aspect of the buttons (hover, etc). 
I wrote a test in `spec/features/animals/index_spec.rb`, however it is not much of a feature test. I was looking for a view spec but didn't see any. Is there a better place to test this functionality? 
Additionally, confirmed in the browser that when clicked you get a page that allows you to upload a csv.
=> adds back in the missing csv upload link

tailwind.config.js
Using the ANDI tool, we've identified accessibility issues. One of those issues existed on the admin/users page related to the headings on the table found there. This pull request fixes https://github.com/rubyforgood/abalone/issues/565 & https://github.com/rubyforgood/abalone/issues/561 & https://github.com/rubyforgood/abalone/issues/554 & https://github.com/rubyforgood/abalone/issues/551 & https://github.com/rubyforgood/abalone/issues/547 & https://github.com/rubyforgood/abalone/issues/543 & https://github.com/rubyforgood/abalone/issues/539. 
This change is made on a site wide basis so that is something to be aware of. I clicked around and didn't see any drastic change. I used the default ANDI color recommended to me, which provides just enough contrast to pass whatever standards ANDI is …
=> changes the caption-light css

Gemfile, app/assets/javascripts/reports.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/reports_kit.scss, app/controllers/reports_controller.rb, app/models/animal.rb, app/models/facility.rb, app/views/layouts/application.html.erb, app/views/reports/index.html.erb, config/routes.rb, spec/controllers/reports_controller_spec.rb, spec/features/reporting_spec.rb
Currently, blazer is not accessible through the site's navigation. This branch offers a possible approach to that by removing the current reports routing and adding `as: reports` to the blazer routes.
An alternative approach can be seen here: https://github.com/ankane/blazer/issues/50#issuecomment-259071162. This appears to requiring forking the gem, which we have avoided doing so far.
@benreyn or @mdworken, any thoughts or preferences on this?
If the proposed option is acceptable, I can finish cleaning it up and prepare a proper PR.
=> Possible path for integrating blazer into the site navigation.

app/views/users/index.html.erb, spec/features/users/index_spec.rb
Resolves #564 
Following the advice in [this guide](https://www.w3.org/WAI/tutorials/tables/one-header/), I've added scope="col" to all table headers. 
Tested using the ANDI accessibility tool to confirm that the warning has disappeared.
=> #564 fix table accessibility issues

app/views/users/index.html.erb, spec/features/users/index_spec.rb
Resolves #563 
'Show' links in Users table triggered ANDI's 'Ambiguous Link' warning. To fix this, I added unique titles to each 'Show' link. 
Tested in the browser using the ANDI accessibility tool.
=> add accessible title to Show link

app/assets/stylesheets/application.scss, app/views/measurements/new.html.erb, spec/features/new_measurements_spec.rb
Resolves #552 
The select element on the 'New Measurements' page was missing a label. To make it accessible, I have added a visually-hidden class to the application styles and used this to add a label that's only visible for screen readers. This class can now be used for any inputs and elements we want to hide in the app.
In the browser, using ANDI.
=> add visually hidden class and label for new measurements

app/views/file_uploads/new.html.erb
Resolves #557 
The file upload input had a corresponding label, but the two weren't associated properly. Because of this, the file upload wasn't accessible. I have updated the label's _for_ property to match the input id. There was no need to update existing unit tests for this and I have not added any new ones, as I didn't think it was necessary.
Tested in the browser, using ANDI.
=> fix label tag for file upload input

app/views/file_uploads/new.html.erb
Resolves #558 
The Submit button on the File Upload page had low color contrast. As this button was styles using Bulma and I noticed you're working on replacing it as part of #466, I updated the button styles with the same class we're using on the 'Change Password' page.
Tested in the browser using ANDI. Color contrast is now sufficient.
I didn't add unit tests for this, as I didn't think it was necessary.
=> update styles to replace bulma and improve color contrast

app/assets/stylesheets/application.scss, app/views/measurements/new.html.erb, spec/features/new_measurements_spec.rb
Resolves #623 
When I added my `.visually-hidden` class to the application styles I didn't realise that this is a duplicate of Tailwind's built-in `.sr-only` (sorry 😬). I've now removed my code and replaced it with `.sr-only`.
Unit tests and ANDI.
=> replace visually-hidden class with Tailwind sr-only class

app/assets/stylesheets/application.scss, app/views/home/index.html.erb, app/views/layouts/application.html.erb, spec/features/home_page_statistics_spec.rb
Resolves #532 and #621
The logo in the navigation was an `h1` element. As we only want one `h1` on every page, and we want this to be the page title, this has been updated to a simple link.
An accessible title has been added to the homepage. This is only visible to screen readers, as sighted users can read the title on the hero banner. At the same time, the card titles and counts were inappropriately wrapped in `h2` and `h1` tags. To improve the structure of the page, these are now simple paragraphs under the 'Your organisation' header. (I originally considered making this a list, but since the cards are built from lots of `div`s I didn't want to have a bunch of list items wrapped in `div`s, as this would look pretty confusing. I also changed the `section` elements to `div`s, as sections …
=> add screen reader-only page title, update cards and page logo

app/views/measurement_types/index.html.erb
Resolves #559 
The 'Delete' and 'Edit' actions in the Measurement Types table did not have any labels or titles. In order to improve accessibility, I followed the recommendations on [W3.org](https://www.w3.org/WAI/GL/wiki/Using_aria-label_for_link_purpose) and added descriptive aria-labels to each link.
Tested with ANDI.
=> add descriptive aria labels to actions in measurement types table

app/assets/stylesheets/application.scss
Resolves #556
The shade of red used on the .button-danger class was too bright. To improve accessibility and get a better contrast ratio, I changed this to a darker shade of red. Now we have a contrast ratio of 4.63:1 (AA for normal text, AAA for large text according to WebAIM).
With WebAIM's contrast checker and with ANDI.
=> update shade of red to pass color contrast check

app/views/enclosures/index.html.erb, spec/features/enclosures/index_spec.rb
Resolves #541 
"Show" links on Enclosures page didn't have unique identifiers. In order to improve accessibility, I have added descriptive aria labels.
Using ANDI
=> add descriptive aria label to Show links

app/views/facilities/index.html.erb, spec/features/facilities/index_spec.rb
Resolves #537 
Show and Location links in Facilities table did not have unique identifiers. To improve accessibility, I've added descriptive aria labels.
Using ANDI
=> add aria labels to facility show and location links

app/views/layouts/application.html.erb, spec/features/home_page_statistics_spec.rb
Resolves #533
I added a `tabindex` attribute to each of the links in the navbar so you can use the keyboard to navigate to any of the links or dropdowns.
I added tests to `spec/features/home_page_statistics_spec.rb`
=> Fix navigation links using tabindex

app/views/animals/index.html.erb, spec/features/animals/index_spec.rb
Resolves #544
Add title to Edit and Delete icons on the Animals index page.
Feature test
=> Add titles to icons on Animals page

app/views/home/index.html.erb, spec/features/home_page_statistics_spec.rb, tailwind.config.js
Contributes to #466
Replaces Bulma classes with TailwindCSS classes in views/home/index.html.erb. I tried to change the style as little as possible.
**Desktop**
**414 x 786**
**768 x 1024**
**1024 x 1366**
=> Replace bulma with tailwind on home/index

app/views/animals/index.html.erb, app/views/cohorts/index.html.erb, app/views/enclosures/index.html.erb, app/views/facilities/index.html.erb, app/views/locations/index.html.erb, app/views/locations/show.html.erb, app/views/measurement_types/index.html.erb, app/views/users/index.html.erb
Resolves #681 
Added a variable width to the edit and delete images on all the tables so these links will not be hidden when the table content size increases. Also I fixed a couple places where the table border was not showing.
=> Fix width of edit/delete links in tables

app/assets/javascripts/navbar.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, spec/features/home_page_statistics_spec.rb, tailwind.config.js
Addresses #680 
- Converted Bulma to TailwindCSS within navbar in layouts/application
- Tested on Chrome and Safari
Fixed existing unit tests
=> convert navbar to tailwindCSS

config/environments/production.rb
- [n/a] I have commented my code, particularly in hard-to-understand areas,
- [n/a] I have made corresponding changes to the documentation,
- [n/a] I have added tests that prove my fix is effective or that my feature works,
- [n/a] Title include "WIP" if work is in progress.
Resolves #704
Forces application over SSL in the production environment. Sets the HSTS header expiration to 0 for future flexibility.
Test suite and rubocop run locally and in CI
=> Force ssl in production. Set HSTS to expire immediately.

app/lib/csv_importer.rb, spec/lib/csv_importer_spec.rb
Resolves #725
This change adds a parameter to the CSV parser that tells it to skip blank lines.
Added a new test to CsvImporterSpec
=> Measurement import should ignore empty lines in the file

README.md
Resolves #733
Documentation change:     
This change adds how to run the ruby test suite for abalone to the getting-started section of the main README.md.
This is helpful information for setting up and validating a development environment before making changes.
Worked through the Getting-Started steps through 'Prerequisites' and 'Setup'.
Started PostgreSQL
Then followed the added Test suite step `bundle exec rake`
All tests passed with this output:
```
Finished in 8.74 seconds (files took 4.78 seconds to load)
151 examples, 0 failures
Coverage report generated for RSpec to ../abalone/coverage. 2134 / 2256 LOC (94.59%) covered.
```
--
Let me know if this change could be accepted (or rejected) or
needs some additional changes to be approved and merged.
Thank you,
DC
=> Add how to run the test suite to getting-started doc

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/controllers/cohort_imports_controller.rb, app/forms/csv_import_form.rb, app/jobs/import_cohorts_job.rb, app/views/cohort_imports/new.html.erb, app/views/cohorts/index.html.erb, config/initializers/simple_form.rb, config/locales/simple_form.en.yml, config/routes.rb, lib/templates/erb/scaffold/_form.html.erb, public/samples/cohort.csv, spec/factories/enclosures.rb, spec/features/cohorts/import_spec.rb, spec/features/cohorts/index_spec.rb, spec/models/cohort_spec.rb
Implemented this based off of the other csv import solutions, although this implementation is a bit different. 
I noticed a lot of common code between the import implementations. I think we could move to dry out and generalize the code across the three in the future. This uses validation logic rather than exception handlers in the import to build the job status response. And a new controller rather than new actions.
I added the simple_form gem to display validation errors on the FE. If this is not desired, I can remove and update.
Resolves #322 
There are automated tests for checking import functionality, and some feature spec to check user interaction. Manually tested and verified.
There are some screenshots in the comments …
=> Import CSV's for Cohort's

app/controllers/file_uploads_controller.rb, app/models/measurement.rb, app/views/file_uploads/show.html.erb, spec/features/file_upload/show_spec.rb
Resolves #711
- Some of the values were not being shown on the `processed_file#show` page because a Measurement's `subject` is polymorphic. So I added three new model functions to find `cohort_name` if the subject is a Cohort, `enclosure_name` if the subject is an Enclosure, and `animal_tag` if the subject is an Animal
- I also added two new delegates because the previous implementation was trying to show `measurement_event` and `measurement_type` which are both objects. So the table will output `measurement_type_name` and `measurement_event_name`
New feature test for file_upload#show
=> Show all imported data on processed_file#show page

app/views/devise/sessions/new.html.erb
Resolves #709 
Resolves #710
- Add `border` to email and password inputs of the login page so they don't disappear into the background
- Add width class `w-44` to email and password inputs of the login page so that Firefox browser design matches Chrome/Safari design
Using Chrome, Safari and Firefox browsers
**Safari**
**Chrome**
**Firefox**
=> Add border and width to login form inputs

spec/features/cohorts/show_spec.rb
Resolves #708 
(fix or feature that would cause existing functionality to not 
This is a fix for the test in feature/cohorts/show_spec . Before the tests were complaining because cohort.enclosure&.name was nil, so there was no point in checking. I added an enclosure to the cohort so that we could check if the name shows up on the page.
=> Fix nil warning for tests be adding an enclosure to cohort

app/views/cohorts/index.html.erb
Resolves #550 
I added the scope attribute to the <th> element for screenreaders and filled the empty header.
=> #550 : add scope="col" and header

app/views/cohorts/index.html.erb
Resolves #549 
I added an aria-label attribute on links to not overload the view for the common use.
=> #549 add aria-label on show links

app/views/animals/index.html.erb
Resolves #545 
I added an aria-label attribute with the tag of the animal on links to not overload the view for the common use.
=> #545 add aria-label attribute on show links

app/views/enclosures/index.html.erb
Resolves #540 
I added an aria-label attribute on links to not overload the view for the common use. I don't have problem with icons on firefox and brave web browsers.
=> #540 add aria-label on links

app/views/file_uploads/csv_index.html.erb
Resolves #553 
I added the scope attribute to the <th> element for screenreaders and filled the empty header.
=> #553 add scope="col" and header

app/views/cohorts/index.html.erb
Resolves #548 
I added an aria-label attribute on links to not overload the view for the common use.
=> #548 add aria-label on links

app/assets/stylesheets/sessions.scss
Resolves #748 
I added `height: -moz-fit-content` to the sessions_container class.
I check the view in the browser before and after the modification.
Firefox before : 
Firefox after :
Brave (chrome based web browser) after is still the same :
=> #748 add -moz-fit-content in sessions_container class

app/views/animals/index.html.erb, app/views/cohorts/index.html.erb, app/views/enclosures/index.html.erb, app/views/facilities/index.html.erb
Resolves : nothing
Just align the actions in index views with the `align-middle` class of tailwind .
Just looking the web browser.
Before :
After :
=> Styling : add vertical align for action buttons in the index views

app/models/cohort.rb, spec/models/cohort_spec.rb
Resolves #437 
Added validations to cohort model for the `:name` property. Model now test for presence of ':name', and will fail out actions that do not set or remove the attribute. ':name' was also set to be unique for the organization the cohort was created for. Multiple organizations can create cohorts with the same ':name', but the ':name' cannot be repeated for that orginization.  
Added validation tests to `cohort_spec.rb`. Used standard shoulda-matcher tests for `:name` presence. 
Shoulda-matcher does not test for uniqueness of attributes scoped to other models, so tests were written ensuring that an instance became invalid if it was a repeated `:name`. A second expectation tests that a `:name` was not locked for other …
=> Name validation

app/controllers/measurement_types_controller.rb, app/models/measurement_type.rb, app/views/measurement_types/index.html.erb, spec/models/measurement_type_spec.rb, spec/requests/measurement_types_controller_spec.rb, spec/system/measurement_types/index_spec.rb
Resolves #901  
With this change, measurement_types cannot be deleted if they have any dependent measurement records. In writing this code, I discovered ActiveRecord's :restrict_with_error association dependency on the model which prevents destruction at a very low level. Issues and errors resulting from a failed attempt to destroy a measurement_type are added to the object's errors for display to users and engineers working with these records. (Sidebar: we may want to circle back to exit_types and apply this same pattern for safer handling of those records outside the Controller. )
New feature / Bug fix
Rspec tests have been added for measurement_type model, controller, and view
=> Resolves #901: Prevent the deletion of Measurement Types that have already been used in measurements

app/controllers/exit_types_controller.rb, app/models/exit_type.rb, spec/models/exit_type_spec.rb
Follow-through related to #901 
This commit moves the ExitType destroy restriction from the exit_types_controller to the model.
Refactor
Additional spec examples added to ExitType model
=> Move exit_type destroy restriction from controller to model

app/controllers/file_uploads_controller.rb, app/jobs/concerns/import_job.rb, app/jobs/mortality_event_job.rb, app/lib/csv_importer.rb, app/lib/file_uploader.rb, app/models/measurement.rb, app/models/mortality_event.rb, spec/fixtures/files/basic_custom_measurement.csv, spec/fixtures/files/basic_custom_measurement_invalid.csv, spec/fixtures/files/basic_custom_mortality_events.csv, spec/jobs/concerns/import_job.rb, spec/lib/csv_importer_spec.rb, spec/models/mortality_event_spec.rb, spec/system/file_upload/new_spec.rb, spec/system/file_upload/show_spec.rb
Resolves #899
This change is necessarily larger than the issue description might imply.
The importing tools were already setup to provide an error message to the user when attempting to import a non-existent measurement_type for a new Measurement record. However, the import tooling had hard-coded a set of allowable measurement_types, likely at a time before Users could create their own custom measurement_types.
This change enables error messaging to Users by providing the following:
* Removes hard-coding of measurement_types
* Decouples CsvImporter from Measurements and MortalityEvents
* Separates the upload of Measurements from MortalityEvents (which now have distinct dropdown options at the ImportFile page)
* Additional expectation was added to an existing spec example in …
=> Resolves #899: Provide Error Message for Invalid Measurement Types in import

Gemfile, Gemfile.lock, app/overrides/controllers/blazer/queries_controller_override.rb
- [n/a] I have made corresponding changes to the documentation,
- [n/a] I have added tests that prove my fix is effective or that my feature works,
- [n/a] Title include "WIP" if work is in progress.
Upgrades the blazer gem to 2.5.0. Confirms that override of the set_queries method does not need any changes. This override is in place to ensure that only queries for the current organization are displayed on the Dashboard. This compliments the database constraints that allow for multi-tenancy in the application.
Existing checks pass. Blazer dashboard manually tested after upgrade.
=> Bump blazer gem to version 2.5.0
